Added pfm_last_modified to all payloads

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -25,7 +25,7 @@ updated_file="false"
 
 # Loop through all plist-files to be commited
 for file in $( git diff --name-only --diff-filter=AM "${against}" | grep '\.plist$' ); do
-	
+		
 	# Get the file name
 	file_name=$( basename "${file}" )
 	
@@ -62,6 +62,18 @@ for file in $( git diff --name-only --diff-filter=AM "${against}" | grep '\.plis
 		if ! /usr/libexec/PlistBuddy -c "Set pfm_version ${version_updated}" "${file}" 2>/dev/null; then
 			printf "%s\n" "$( basename ${file} ): Failed to set value: ${version_updated} for key: pfm_version"
 			exit 1
+		fi
+		
+		# Get the value of the pfm_last_modified key
+		file_last_modified=$( /usr/libexec/PlistBuddy -c "Print pfm_last_modified" "${file}" 2>/dev/null )
+
+		# Verify the value returned is valid
+		if [[ -z ${file_last_modified} ]] && ! /usr/libexec/PlistBuddy -c "Add pfm_last_modified date $( LANG=C /bin/date +%a" "%b" "%d" "%T" "%Z" "%Y )" "${file}"; then
+			printf "%s\n" "${file_name}: Failed to add value: $( LANG=C /bin/date +%a" "%b" "%d" "%T" "%Z" "%Y ) for key: pfm_last_modified"
+			exit 1
+		elif ! /usr/libexec/PlistBuddy -c "Set pfm_last_modified date $( LANG=C /bin/date +%a" "%b" "%d" "%T" "%Z" "%Y )" "${file}"; then
+			printf "%s\n" "${file_name}: Failed to add value: $( LANG=C /bin/date +%a" "%b" "%d" "%T" "%Z" "%Y ) for key: pfm_last_modified"
+			exit 1	
 		fi
 		
 		updated_file="true"
diff --git a/updateIndex b/updateIndex
--- a/updateIndex
+++ b/updateIndex
@@ -61,7 +61,13 @@ for directory_name in ${manifest_directories[@]}; do
 		fi
 		
 		# Get the last modification time of the file
-		file_modified=$( date -r ${file} )
+		file_last_modified=$( /usr/libexec/PlistBuddy -c "Print pfm_last_modified" "${file}" 2>/dev/null )
+		
+		# Verify the value returned is valid
+		if [[ -z ${file_last_modified} ]] && ! /usr/libexec/PlistBuddy -c "Add pfm_last_modified date $( LANG=C /bin/date +%a" "%b" "%d" "%T" "%Z" "%Y )" "${file}"; then
+			printf "%s\n" "${file_name}: Failed to add value: $( LANG=C /bin/date +%a" "%b" "%d" "%T" "%Z" "%Y ) for key: pfm_last_modified"
+			exit 1
+		fi
 		
 		# Create the file dictionary
 		if ! /usr/libexec/PlistBuddy -c "Add :${directory_name}:${file_domain} dict" "${index_path_tmp}"; then
@@ -88,7 +94,7 @@ for directory_name in ${manifest_directories[@]}; do
 		fi
 		
 		# Add the file last modified
-		if ! /usr/libexec/PlistBuddy -c "Add :${directory_name}:${file_domain}:modified date ${file_modified}" "${index_path_tmp}"; then
+		if ! /usr/libexec/PlistBuddy -c "Add :${directory_name}:${file_domain}:modified date ${file_last_modified}" "${index_path_tmp}"; then
 			printf "%s\n" "${file_name}: Failed to add value: ${directory_name}/${file_name} for key: ${directory_name}:${file_domain}:modified"
 			exit 1
 		fi
