Added output

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -83,10 +83,13 @@ done
 if [[ ${updated_file} == true ]]; then
 	if [[ -f ${repository_path}/updateIndex ]]; then
 		if ! "${repository_path}/updateIndex"; then
-			printf "%s\n" "Failed to run updateIndex"
+			printf "%s\n" "Failed to run updateIndex at ${repository_path}/updateIndex"
+			exit 2
 		fi
 	else
 		printf "%s\n" "${repository_path}/updateIndex: No such file or directory"
+		exit 2
 	fi
-	exit 1
+	printf "%s\n" "Updated version and date information in commited manifests, please press commit again to include the added changes."
+	exit 3
 fi
