Added path to icon index

diff --git a/updateIndexIcons b/updateIndexIcons
--- a/updateIndexIcons
+++ b/updateIndexIcons
@@ -55,6 +55,12 @@ for directory_name in ${manifest_directories[@]}; do
 			printf "%s\n" "${file_name}: Failed to add value: ${file_hash} for key: ${directory_name}:${file_domain}:hash"
 			exit 1
 		fi
+		
+		# Add the file path
+		if ! /usr/libexec/PlistBuddy -c "Add :${directory_name}:${file_domain}:path string Icons/${directory_name}/${file_name}" "${index_path_tmp}"; then
+			printf "%s\n" "${file_name}: Failed to add value: ${directory_name}/${file_name} for key: ${directory_name}:${file_domain}:path"
+			exit 1
+		fi
 	done
 done
 
