Changed from filename to path for easier access

diff --git a/updateIndex b/updateIndex
--- a/updateIndex
+++ b/updateIndex
@@ -79,8 +79,8 @@ for directory_name in ${manifest_directories[@]}; do
 		fi
 		
 		# Add the file name
-		if ! /usr/libexec/PlistBuddy -c "Add :${directory_name}:${file_domain}:filename string ${file_name}" "${index_path_tmp}"; then
-			printf "%s\n" "${file_name}: Failed to add value: ${file_hash} for key: ${directory_name}:${file_domain}:filename"
+		if ! /usr/libexec/PlistBuddy -c "Add :${directory_name}:${file_domain}:path string ${directory_name}/${file_name}" "${index_path_tmp}"; then
+			printf "%s\n" "${file_name}: Failed to add value: ${directory_name}/${file_name} for key: ${directory_name}:${file_domain}:filename"
 			exit 1
 		fi
 	done
